### PR TITLE
Name of the parent element was being passed instead of the current ch…

### PR DESCRIPTION
**Pull request by longjos**
…ild resulting in an infinite loop

### CODE REVIEW

**Review by joyrexus — COMMENTED** [review]
Interesting.  Curious how you caught this?

Yeah, confirmed that the optout and optin calls do appear to work fine with this commit.

The only thing I'm a bit unclear about is the various tests in `test/request-response-samples-test.js` and `test/wsdl-test.js` that are now failing.  Did you notice that?

From a quick glance I couldn't tell if the tests failures are innocuous ... or point to problematic side effects of this change.

**Comment by longjos** [comment]
> > Interesting. Curious how you caught this?

A lot of time in the debugger. 

> > The only thing I'm a bit unclear about is the various tests in test/request-response-samples-test.js and test/wsdl-test.js that are now failing. Did you notice that?
> > 
> > From a quick glance I couldn't tell if the tests failures are innocuous ... or point to problematic side effects of this change.

The tests in this repo didn't immediately run, so I only tested against the mindbody_client tests.
I'll try to get the node_soap tests working and see what the side effects may be.

**Comment by longjos** [comment]
It's hard to tell if my change "broke" anything.... It could take hours of more digging around to see "how" this is supposed to work. I would propose we go ahead with the change as long as our client tests pass. Probably need to open a ticket with the library developers since they will be more familiar with what is going on.

**Comment by joyrexus** [comment]
Alright, yeah ... I hadn't run all the client lib tests, only `/test/service/client`.  They're all passing with the change.

I'll merge so we can have the optout/optin calls.

**Comment by joyrexus** [comment]
Example of one of the tests that's failing (`Request Response Sampling ref element should has correct namespace`) at `/test/request-response-samples-test.js:57`:

Expected ...

``` xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dummy="http://www.Dummy.com" xmlns:tns="http://www.Dummy.com" xmlns:common="http://www.Dummy.com/Common">
<soap:Body>
  <dummy:DummyRequest xmlns:dummy="http://www.Dummy.com" xmlns="http://www.Dummy.com">
    <common:Order xmlns:common="http://www.Dummy.com/Common"><common:Id>1</common:Id><common:Name>foo</common:Name></common:Order>
  </dummy:DummyRequest>
</soap:Body>
</soap:Envelope>
```

Actual ...

``` xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dummy="http://www.Dummy.com" xmlns:tns="http://www.Dummy.com" xmlns:common="http://www.Dummy.com/Common">
<soap:Body>
  <dummy:DummyRequest xmlns:dummy="http://www.Dummy.com" xmlns="http://www.Dummy.com">
    <dummy:Order><dummy:Id>1</dummy:Id><dummy:Name>foo</dummy:Name></dummy:Order>
  </dummy:DummyRequest>
</soap:Body>
</soap:Envelope>
```

So, looks like the change results in all child elements inheriting the namespace of their parent elements?

**Pull request merged**
